In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Preconfiguring packages ...
Selecting previously unselected package cron.
(Reading database ... 18408 files and directories currently installed.)
Preparing to unpack .../00-cron_3.0pl1-128ubuntu5_amd64.deb ...
Unpacking cron (3.0pl1-128ubuntu5) ...
Selecting previously unselected package libapparmor1:amd64.
Preparing to unpack .../01-libapparmor1_2.11.0-2ubuntu17.1_amd64.deb ...
Unpacking libapparmor1:amd64 (2.11.0-2ubuntu17.1) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../02-libdbus-1-3_1.10.22-1ubuntu1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../03-dbus_1.10.22-1ubuntu1_amd64.deb ...
Unpacking dbus (1.10.22-1ubuntu1) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../04-dirmngr_2.1.15-1ubuntu8.1_amd64.deb ...
Unpacking dirmngr (2.1.15-1ubuntu8.1) ...
Selecting previously unselected package distro-info-data.
Preparing to unpack .

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
path = "drive/colab/JUSTCODEIT/"

In [0]:
data = pd.read_csv(path+'bangalore-cas-alerts.csv')

In [6]:
data.head()

deviceCode_deviceCode  deviceCode_location_latitude  \
0        864504031502210                     12.984595   
1        864504031502210                     12.984595   
2        864504031502210                     12.987233   
3        864504031502210                     12.987233   
4        864504031502210                     12.987503   

   deviceCode_location_longitude deviceCode_location_wardName  \
0                      77.744087                     Kadugodi   
1                      77.744087                     Kadugodi   
2                      77.741119             Garudachar Playa   
3                      77.741119             Garudachar Playa   
4                      77.740051                         Hudi   

  deviceCode_pyld_alarmType  deviceCode_pyld_speed  \
0                       PCW                     32   
1                       PCW                     32   
2                       FCW                     41   
3                       FCW                     41   
4                 Overspeed                     37   

  deviceCode_time_recordedTime_$date  
0           2018-02-01T01:48:59.000Z  
1           2018-02-01T01:48:59.000Z  
2           2018-02-01T01:50:00.000Z  
3           2018-02-01T01:50:00.000Z  
4           2018-02-01T01:50:11.000Z

In [10]:
data.count()

deviceCode_deviceCode                 207617
deviceCode_location_latitude          207617
deviceCode_location_longitude         207617
deviceCode_location_wardName          207617
deviceCode_pyld_alarmType             207617
deviceCode_pyld_speed                 207617
deviceCode_time_recordedTime_$date    207617
dtype: int64

In [11]:
co = data.columns
co

Index(['deviceCode_deviceCode', 'deviceCode_location_latitude',
       'deviceCode_location_longitude', 'deviceCode_location_wardName',
       'deviceCode_pyld_alarmType', 'deviceCode_pyld_speed',
       'deviceCode_time_recordedTime_$date'],
      dtype='object')

In [12]:
for i in (co):
  print(data[i].nunique())

26
47270
18007
50
7
82
134441


In [0]:
y = data.iloc[:,4].values

In [14]:
y

array(['PCW', 'PCW', 'FCW', ..., 'Overspeed', 'FCW', 'PCW'], dtype=object)

In [0]:
data = data.drop(columns=["deviceCode_pyld_alarmType"])

In [46]:
data.tail()

deviceCode_deviceCode  deviceCode_location_latitude  \
207612        864504031432707                     12.976435   
207613        864504031035658                     12.986425   
207614        863977033828919                     12.969396   
207615        863977033715231                     12.974123   
207616        863977033827523                     12.975480   

        deviceCode_location_longitude deviceCode_location_wardName  \
207612                      77.741516                     Kadugodi   
207613                      77.745117                     Kadugodi   
207614                      77.749886                      Hagadur   
207615                      77.746841                      Hagadur   
207616                      77.744125                      Hagadur   

        deviceCode_pyld_speed deviceCode_time_recordedTime_$date  
207612                      0                              10:56  
207613                     12                              11:07  
207614                     17                              11:14  
207615                     36                              11:16  
207616                     28                              11:25

In [0]:
data["deviceCode_time_recordedTime_$date"]=data["deviceCode_time_recordedTime_$date"].apply(lambda s: s[11:16])

In [38]:
data.iloc[207491,5]

'11:13'

In [0]:
def cor(s):
  if int(s[3])<3:
    return int(s[0:2])
  else:
    return int(s[0:2])+1
  

In [0]:
data["deviceCode_time_recordedTime_$date"]=data["deviceCode_time_recordedTime_$date"].apply(lambda s: cor(s))

In [48]:
data.head()

deviceCode_deviceCode  deviceCode_location_latitude  \
0        864504031502210                     12.984595   
1        864504031502210                     12.984595   
2        864504031502210                     12.987233   
3        864504031502210                     12.987233   
4        864504031502210                     12.987503   

   deviceCode_location_longitude deviceCode_location_wardName  \
0                      77.744087                     Kadugodi   
1                      77.744087                     Kadugodi   
2                      77.741119             Garudachar Playa   
3                      77.741119             Garudachar Playa   
4                      77.740051                         Hudi   

   deviceCode_pyld_speed  deviceCode_time_recordedTime_$date  
0                     32                                   2  
1                     32                                   2  
2                     41                                   2  
3                     41                                   2  
4                     37                                   2

In [49]:
cols = data.columns
num_cols = data._get_numeric_data().columns
co = list(set(cols) - set(num_cols))
co

['deviceCode_location_wardName']

In [0]:
co.append("deviceCode_deviceCode")

In [51]:
co

['deviceCode_location_wardName', 'deviceCode_deviceCode']

In [0]:
X = data.iloc[:,:].values

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
for c in co:
  cc= data.columns.get_loc(c)
  X[:,cc] = labelencoder_X.fit_transform(X[:,cc])

In [55]:
X[0]

array([23, 12.98459529876709, 77.74408721923828, 31, 32, 2], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [57]:
y

array([5, 5, 0, ..., 4, 0, 5])

In [58]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6])

In [59]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [0]:
!apt-get -qq install --no-install-recommends nvidia-375
!apt-get -qq install --no-install-recommends nvidia-opencl-icd-375 nvidia-opencl-dev opencl-headers
!apt-get -qq install --no-install-recommends git cmake build-essential libboost-dev libboost-system-dev libboost-filesystem-dev
!pip3 install -qq lightgbm --install-option=--gpu

In [0]:
import lightgbm as lgb

In [0]:
train_data = lgb.Dataset(X_train, label=y_train)
test_data = train_data.create_valid(X_test,label=y_test)

In [0]:
param = {'num_leaves':512, 'num_trees':329, 'objective':'multiclass', 'num_class':7,'maxbin':2048}
param['metric'] = 'multi_logloss'

In [88]:
num_round = 475
bst = lgb.train(param, train_data, num_round, valid_sets=[test_data])

/usr/local/lib/python3.6/dist-packages/lightgbm/engine.py:102: UserWarning: Found `num_trees` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


[1]	valid_0's multi_logloss: 1.77607
[2]	valid_0's multi_logloss: 1.64583
[3]	valid_0's multi_logloss: 1.54015
[4]	valid_0's multi_logloss: 1.45136
[5]	valid_0's multi_logloss: 1.37573
[6]	valid_0's multi_logloss: 1.31059
[7]	valid_0's multi_logloss: 1.25335
[8]	valid_0's multi_logloss: 1.20265
[9]	valid_0's multi_logloss: 1.15779
[10]	valid_0's multi_logloss: 1.11768
[11]	valid_0's multi_logloss: 1.08182
[12]	valid_0's multi_logloss: 1.04929
[13]	valid_0's multi_logloss: 1.01979
[14]	valid_0's multi_logloss: 0.993256
[15]	valid_0's multi_logloss: 0.969038
[16]	valid_0's multi_logloss: 0.946547
[17]	valid_0's multi_logloss: 0.926025
[18]	valid_0's multi_logloss: 0.907372
[19]	valid_0's multi_logloss: 0.890375
[20]	valid_0's multi_logloss: 0.874652
[21]	valid_0's multi_logloss: 0.860384
[22]	valid_0's multi_logloss: 0.847089
[23]	valid_0's multi_logloss: 0.834519
[24]	valid_0's multi_logloss: 0.822791
[25]	valid_0's multi_logloss: 0.81204
[26]	valid_0's multi_logloss: 0.802039
[27]	vali

In [0]:
y_pred = bst.predict(X_test)
y_pred = np.argmax(y_pred,axis=1)

In [90]:
y_pred

array([0, 6, 6, ..., 6, 2, 5])

In [91]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 79.66%
